-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

CREATE TABLE IF NOT EXISTS public.archivo_delete_requests
(
    id serial NOT NULL,
    archivo_id integer NOT NULL,
    solicitado_por integer,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pendiente'::character varying,
    motivo text COLLATE pg_catalog."default",
    solicitado_at timestamp without time zone DEFAULT now(),
    resuelto_por integer,
    resuelto_at timestamp without time zone,
    comentario_admin text COLLATE pg_catalog."default",
    observacion_id integer,
    CONSTRAINT archivo_delete_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.archivos_historial
(
    id serial NOT NULL,
    razon_social_id integer,
    usuario_id integer,
    nombre_archivo character varying(500) COLLATE pg_catalog."default" NOT NULL,
    nombre_almacenado character varying(500) COLLATE pg_catalog."default" NOT NULL,
    storage_key character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    storage_url text COLLATE pg_catalog."default",
    anio integer NOT NULL,
    mes integer NOT NULL,
    tamano bigint,
    uploaded_at timestamp without time zone DEFAULT now(),
    empresa_id integer,
    CONSTRAINT archivos_historial_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.empresa
(
    id serial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    razon_social_id integer,
    carpeta character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT empresa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.numeros_parte
(
    id serial NOT NULL,
    numero_parte character varying(120) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default",
    usuario_id integer,
    razon_social_id integer,
    empresa_id integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT numeros_parte_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.observacion_mensajes
(
    id serial NOT NULL,
    observacion_id integer NOT NULL,
    iduser integer,
    mensaje character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT observacion_mensajes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.observaciones
(
    id serial NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default",
    iduser integer,
    idarchivo integer,
    created_at timestamp with time zone DEFAULT now(),
    status character varying(500) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'abierto'::character varying,
    cliente_participante_id integer,
    CONSTRAINT observaciones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.razon_social
(
    id serial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    r2_folder character varying(500) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT razon_social_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL,
    nombrerol character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    nombre_usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    alias character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    empresa_id integer,
    rol integer,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_nombre_usuario_key UNIQUE (nombre_usuario)
);

ALTER TABLE IF EXISTS public.archivo_delete_requests
    ADD CONSTRAINT archivo_delete_requests_archivo_id_fkey FOREIGN KEY (archivo_id)
    REFERENCES public.archivos_historial (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_archivo_delete_requests_pending_unique
    ON public.archivo_delete_requests(archivo_id);


ALTER TABLE IF EXISTS public.archivo_delete_requests
    ADD CONSTRAINT archivo_delete_requests_observacion_id_fkey FOREIGN KEY (observacion_id)
    REFERENCES public.observaciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.archivo_delete_requests
    ADD CONSTRAINT archivo_delete_requests_resuelto_por_fkey FOREIGN KEY (resuelto_por)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.archivo_delete_requests
    ADD CONSTRAINT archivo_delete_requests_solicitado_por_fkey FOREIGN KEY (solicitado_por)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.archivos_historial
    ADD CONSTRAINT archivos_historial_empresa_id_fkey FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_historial_empresa
    ON public.archivos_historial(empresa_id);


ALTER TABLE IF EXISTS public.archivos_historial
    ADD CONSTRAINT archivos_historial_razon_social_id_fkey FOREIGN KEY (razon_social_id)
    REFERENCES public.razon_social (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_historial_razon_social
    ON public.archivos_historial(razon_social_id);


ALTER TABLE IF EXISTS public.archivos_historial
    ADD CONSTRAINT archivos_historial_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_historial_usuario
    ON public.archivos_historial(usuario_id);


ALTER TABLE IF EXISTS public.empresa
    ADD CONSTRAINT empresa_razon_social_id_fkey FOREIGN KEY (razon_social_id)
    REFERENCES public.razon_social (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.numeros_parte
    ADD CONSTRAINT numeros_parte_empresa_id_fkey FOREIGN KEY (empresa_id)
    REFERENCES public.empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_numeros_parte_empresa
    ON public.numeros_parte(empresa_id);


ALTER TABLE IF EXISTS public.numeros_parte
    ADD CONSTRAINT numeros_parte_razon_social_id_fkey FOREIGN KEY (razon_social_id)
    REFERENCES public.razon_social (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_numeros_parte_razon_social
    ON public.numeros_parte(razon_social_id);


ALTER TABLE IF EXISTS public.numeros_parte
    ADD CONSTRAINT numeros_parte_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.observacion_mensajes
    ADD CONSTRAINT observacion_mensajes_iduser_fkey FOREIGN KEY (iduser)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.observacion_mensajes
    ADD CONSTRAINT observacion_mensajes_observacion_id_fkey FOREIGN KEY (observacion_id)
    REFERENCES public.observaciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.observaciones
    ADD CONSTRAINT observaciones_cliente_participante_id_fkey FOREIGN KEY (cliente_participante_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
